name: magnit_shop_test
description: Magnit Test

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hive: 2.2.3
  hive_flutter: ^1.1.0
  
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.3
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  injectable: ^1.5.0
  flutter_gen: ^4.1.6
  flutter_dotenv: ^5.0.2
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.5
  flutter_gen_runner: ^4.1.6
  flutter_lints: ^2.0.1
  freezed: ^2.0.3+1
  injectable_generator: ^1.5.2
  json_serializable: ^6.1.5
  bloc_test: ^9.0.1
  extra_pedantic: ^2.0.0

  hive_generator: ^1.1.3

flutter:
  uses-material-design: true